import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// This layout not going to have and ui component but, context providers, fundamental styles, and other things that we want to be available to all pages.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="sm:bg-blue-400 lg:bg-red-400">{children}</body>
    </html>
  );
}
